<script type="text/javascript">
//<![CDATA[
    function locationChanged(element, url, updateId) {

        if(element.value) {
            var loader = new varienLoader(true);
            loader.load(url + "parent/" + element.value, {}, refreshUpdateField);
        } else {
            refreshUpdateField('[]');
        }
        
        function refreshUpdateField(serverResponse) {
            if (!serverResponse)
                return;
            
            var data = eval('(' + serverResponse + ')');
            var updateField = document.getElementById(updateId);
            //updateField.options[0].selected = 'selected';
            updateField.options.length = 1;
            console.log(updateField);
            if (data.length) {
                for (var i in data)
                    updateField.options[i] = new Option(data[i].label, data[i].value);
            }
            
            if(updateField.onchange)
                updateField.onchange();
        }
    }
//]]>
</script>