<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title><?php echo Mage::helper('SunshineBiz_Permission_Helper_Data')->__('Eprint Backend admin') ?></title>
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('reset.css') ?>" media="all" />
    <link type="text/css" rel="stylesheet" href="<?php echo $this->getSkinUrl('boxes.css') ?>" media="all" />
    <!--  
    <link rel="icon" href="<?php echo $this->getSkinUrl('Mage_Page::favicon.ico') ?>" type="image/x-icon" />
    <link rel="shortcut icon" href="<?php echo $this->getSkinUrl('Mage_Page::favicon.ico') ?>" type="image/x-icon" />
	-->
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('prototype/prototype.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('prototype/validation.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('scriptaculous/effects.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('mage/adminhtml/form.js') ?>"></script>
    <script type="text/javascript" src="<?php echo $this->getSkinUrl('mage/captcha.js') ?>"></script>

    <!--[if IE]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('iestyles.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if lt IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('below_ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <!--[if IE 7]> <link rel="stylesheet" href="<?php echo $this->getSkinUrl('ie7.css') ?>" type="text/css" media="all" /> <![endif]-->
    <style>
		.login-container-1{ width:581px; margin:170px auto; padding-left:32px; }
		.login-container-1 .legal-1{ margin:0; background:url(<?php echo $this->getSkinUrl('images/login_box_legal_bg.gif') ?>) no-repeat; padding:8px 8px 5px 8px; font-size:.95em; }
	</style>
</head>

<body id="page-login" onload="document.forms.loginForm.username.focus();">
<div class="login-container-1">
    <div class="login-box">
        <form method="post" action="" id="loginForm">
            <div class="login-form">
                <input name="form_key" type="hidden" value="<?php echo $this->getFormKey() ?>" />
                <h2><?php echo Mage::helper('SunshineBiz_Permission_Helper_Data')->__('Eprint Backend admin') ?></h2>
                <div id="messages">
                    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
                </div>
                <div class="input-box input-left"><label for="username"><?php echo Mage::helper('SunshineBiz_Permission_Helper_Data')->__('User Name:') ?></label><br/>
                    <input type="text" id="username" name="login[username]" value="" class="required-entry input-text" /></div>
                <div class="input-box input-right"><label for="login"><?php echo Mage::helper('SunshineBiz_Permission_Helper_Data')->__('Password:') ?></label><br />
                    <input type="password" id="login" name="login[password]" class="required-entry input-text" value="" /></div>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <div class="clear"></div>
                <div class="form-buttons">
                    <?php echo $this->getChildHtml('form.buttons'); ?>
                </div>
            </div>
            <p class="legal-1"><?php echo Mage::helper('SunshineBiz_Permission_Helper_Data')->__('Copyright &copy; %s Eprint.so', date('Y')) ?></p>
        </form>
        <div class="bottom"></div>
        <script type="text/javascript">
            var loginForm = new varienForm('loginForm');
        </script>
    </div>
</div>
</body>
</html>
